### ISSUE TITLE
sox depends not installed

### ISSUE THREAD

**Issue by obbardc** [pideck/pideck#39] opened 2016-12-25 09:30 UTC
For some reason libsox-fmt-alsa was not pulled in as a dependency for the latest image.

```
pi@pideck:~$ dpkg -l | grep sox
ii  libsox-fmt-base:armhf          14.4.1-5                        armhf        Minimal set of SoX format libraries
ii  libsox-fmt-pulse:armhf         14.4.1-5                        armhf        SoX PulseAudio format I/O library
ii  libsox2:armhf                  14.4.1-5                        armhf        SoX library of audio effects and processing
ii  sox                            14.4.1-5                        armhf        Swiss army knife of sound processing
```
This confirms sox is installed in the latest image; but we are installing `libsox-fmt-pulse` instead of `libsox-fmt-alsa`.

Should we add in `libsox-fmt-alsa` as a dependency before `sox` in Pideck?

**Comment by danielhjames** [comment] 2016-12-26 19:14
Hi Chris, I also noticed this, it is because any one of four packages can satisfy the dependency:
https://packages.debian.org/jessie/sox

Should be fixed in https://github.com/pideck/pideck/commit/f95b392d4fdc7a0a510dee279b5dcdb753bef431

**Comment by danielhjames** [comment] 2018-05-30 14:34
Confirmed fixed in pideck_alpha_v2.img, thanks Chris!

**Closed as completed by danielhjames** 2018-05-30 14:34 UTC
Labels: bug
