### ISSUE TITLE
Latest version link?

### ISSUE THREAD

**Issue by carlosguerra3** [pideck/pideck#61] opened 2017-05-17 03:56 UTC
Hi,

What's the latest version of the piDeck?

I think I'm using 0.1 or the one on the official page.

**Comment by danielhjames** [comment] 2017-05-24 16:51
Hi Carlos, 0.1 is the latest official release, if you follow this GitHub project you will see some improvements to soundcard detection and recording etc. Thanks for asking!

**Comment by carlosguerra3** [comment] 2017-05-24 17:57
Hey Daniel thanks for the reply, I was asking because I remember that I reported some problems with the audioinjector and a Class Compliant Sound Card and after that I received a reply with a link for a fix that resolved my problem but those links are now broken.

Are those fixes implemented later on on the official release? I'm using the "fixed" build on my MicroSD but if I download the official release would I loose those fixes?

**Comment by danielhjames** [comment] 2017-05-25 15:59
Sorry, those broken links were for test images which are after the 0.1 release, so if you downloaded 0.1 you would not get the benefit of those fixes. They will be included in the next official release, which I think will be 0.2 ;-)

**Comment by carlosguerra3** [comment] 2017-05-30 03:06
Cool! Thanks!

**Comment by danielhjames** [comment] 2018-05-17 16:27
This is a duplicate of https://github.com/pideck/pideck/issues/60

**Closed as completed** 2018-05-17 16:26 UTC
